### PR TITLE
Remove reference to issue #2

### PR DESCRIPTION
**Pull request by skade**
According to issue #2, this limitation is fixed.

### CODE REVIEW

**Comment by dalgibbard** [comment]
Not quite I'm afraid; what was fixed was the handling of characters within a document; the the original ticket was for the handling of binary attachments, which are a different ordeal. Given some time, this is something I'd like to see implemented; probably by capturing a list of documents with attachments, backing them up to a set dir; and then reattaching them after a successful import.

It's in my head anyway :)

**Comment by mathiasbraeckow** [comment]
isn't that simply an issue of the script just pulling the docs and not the attachments ?
   line 235  # Grab our data from couchdb
   line 236  curl ${curlopt} -X GET "$url/$db_name/_all_docs?include_docs=true" -o ${file_name}
   line 237  # Check for curl errors

Ref. https://wiki.apache.org/couchdb/HTTP_Document_API#Attachments
   When retrieving documents, the attachment's actual data is not included by default, only the metadata. The actual data can be fetched by a GET to the attachment's URL as described in the previous section. 
So if you change line 236
   line 235  # Grab our data from couchdb
   line 236  curl ${curlopt} -X GET "$url/$db_name/_all_docs?include_docs=true&attachments=true" -o ${file_name}
   line 237  # Check for curl errors

Your bash script will dump the attachments in a format it allows the -r to reimport
################################
It seems to work with my test/verify installation
Server
        Centos 7 in Oracle virtual Box
        CouchDB couchdb-1.6.1-1.el7.x86_64
Client
        GNU bash, Version 4.1.17(9)-release (x86_64-unknown-cygwin)
        curl 7.39.0 (x86_64-unknown-cygwin) libcurl/7.39.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.2

#!/usr/bin/bash
# Populate my CouchDB with some Data
USER="<some USR>"
PASSWD="<some PW>"
sender()
{
  COUCHDB[0]="at.couchdb-test.net"
  COUCHDB[1]="de.couchdb-test.net"
  COUCHDB[2]="dk.couchdb-test.net"
  COUCHDB[3]="ru.couchdb-test.net"
  COUCHDB[4]="uk.couchdb-test.net"
  COUCHDB[5]="it.couchdb-test.net"
  COUCHDB[6]="pt.couchdb-test.net"
  COUCHDB[7]="es.couchdb-test.net"
  i=0
  while read line ; do
    if [ 1 ] ; then
      dir=$(dirname         "${line}" )
      md5=$(md5sum --binary "${line}"|cut -f1 -d\ )
      size=$(stat --format="%s" "${line}" )
      pat=$(basename        "${line}" )
      if [ ${size} -lt $(expr 8192 \* 1024 ) ] ; then
        DOC=$(printf "{ \042path\042:\042%s\042"                "${dir}")
        DOC="${DOC}"$(printf ", \042fname\042:\042%s\042"       "${pat}")
        DOC="${DOC}"$(printf ", \042md5\042:\042%s\042"         "${md5}")
        DOC="${DOC}"$(printf ", \042size\042:\042%d\042"        "${size}")
        DOC="${DOC}"$(printf ", \042_attachments\042: {\n")
        DOC="${DOC}"$(printf "    \042%4.4x%4.4x\042: {\n"      "${RANDOM}" "${RANDOM}")
        DOC="${DOC}"$(printf "      \042content-type\042:\042text\/plain\042,\n")
        DOC="${DOC}"$(printf "      \042data\042: \042%s\042\n" $(openssl base64 <"${line}"|tr '\012' ' '|sed 's/ //g'))
        DOC="${DOC}"$(printf "    }\n")
        DOC="${DOC}"$(printf "  }\n")
        DOC="${DOC}"$(printf "}")
        DOCID=$(printf "%4.4x-%4.4x-%4.4x-%4.4x-%4.4x" "${RANDOM}" "${RANDOM}" "${RANDOM}" "${RANDOM}" "${RANDOM}")
        curl --request PUT http://${USER}:${PASSWORD}@${COUCHDB[${i}]}:5984/${DOCID}/ -H 'Content-Type: application/json' -d "${DOC}"
        i=$(expr ${i} + 1 )
        if [ ${i} -ge 8 ] ; then
          i=0
        fi
      fi
    fi
  done
}

cd c:
find  / -type f 2>/dev/null -print| sender

**Comment by dalgibbard** [comment]
Tested this just now;
* Created a database with some binary attachments (Type: application/octet-stream)
* Exported with the ```&attachments=true``` option appended to the export curl call
* Imported to a separate (blank) DB
* Downloaded the binary attachments
* Compared binaries against the originals.

All good!
I'll raise a merge for this shortly. Yay! Nice catch @mathiasbraeckow !

**Comment by dalgibbard** [comment]
Merged.

**Comment by csgui** [comment]
Hello!

`attachments=true` in view API endpoints only works for CouchDB versions **above** `1.6.0`.

[Here](https://issues.apache.org/jira/browse/COUCHDB-1923) you have more information about this feature.

Thanks!

**Pull request merged**
