### PR TITLE
refactor check os type

### PR DESCRIPTION
**Pull request by splanquart**
I think this is better way to check OS type.

### CODE REVIEW

**Comment by dalgibbard** [comment]
Minor thing; could you wrap the second if statement's $os_type in quotes? Just if it is null for any reason, the if statement will error :)

**Comment by splanquart** [comment]
Ok

**Comment by dalgibbard** [comment]
Many thanks!

**Comment by danielebailo** [comment]
well done!

Daniele

http://www.danielebailo.it/


2015-11-01 23:24 GMT+01:00 Darren Gibbard <notifications@github.com>:

**Pull request merged**
