### PR TITLE
Optimized stage 1 reg-exp

### PR DESCRIPTION
**Pull request by peteruithoven**
See:  #68

### CODE REVIEW

**Comment by dalgibbard** [comment]
Just pending confirmation of basic testing in #68 -- could you also update the minor version on line25 to 1.1.8 please? :)

**Comment by peteruithoven** [comment]
I've tested this with a couple of my databases and this seems to work properly.

**Comment by peteruithoven** [comment]
I've updated the version number.

**Comment by dalgibbard** [comment]
LGTM

**Pull request merged**
